# Generated by Django 5.2.4 on 2025-07-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diet_choice',
            field=models.CharField(choices=[('normal', 'Normal'), ('lose_fat', 'Lose Fat')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_protein',
            field=models.PositiveIntegerField(default=132),
        ),
    ]
